### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by hamisirizwan** [SpaceyaTech/SYT-Web-Redesign#8]
- [ ] Hero Banner 1
- [ ] Hero Banner 2
- [ ] Mission&Vision Section
- [ ] Our Leadership Section
- [ ] Partner CTA Section
- [ ] Creative Team
-

**Comment by DennohKim** [comment]
Kindly assign me this page so that I can start working on it. Thanks.

**Comment by hamisirizwan** [comment]
hello @DennohKim . Confirm your availabilty so i can assign the issue to you

**Comment by sonylomo** [comment]
I'm available 👋🏾

**Comment by sonylomo** [comment]
Hey @hamisirizwan 
<img width="456" alt="Screenshot 2023-06-22 at 2 52 23 PM" src="https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/49971500/a305d368-80de-430a-a050-d2dbce0198a8">
<img width="456" alt="Screenshot 2023-06-22 at 2 52 06 PM" src="https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/49971500/1586ed0e-0001-4737-b695-8ba816ba3edf">

I need to export the background vectors of the mission and vision statements. However, they haven't been grouped appropriately in that, vision background vectors should be together and mission background vectors should be together.
<img width="1398" alt="Screenshot 2023-06-22 at 2 54 22 PM" src="https://github.com/SpaceyaTech/SYT-Web-Redesign/assets/49971500/dd1339ad-7e63-41c8-a9ab-ab96fe4f3567">

Since I don't have edit access on Figma, could you please group them for me or give me edit access (sonylomo1@gmail.com)?

**Comment by hamisirizwan** [comment]
hello sonia, please create a copy of the design so you can group what you
need to export

**Comment by sonylomo** [comment]
I'm working on the carousel for images on _Leadership section_ and _Creative team_.

**Comment by hamisirizwan** [comment]
did you manage grouping the components in figma?

**Comment by hamisirizwan** [comment]
@sonylomo how long with the leadership and creative section take you?

**Comment by sonylomo** [comment]
Yeah, I figured it out.

**Comment by sonylomo** [comment]
@hamisirizwan, I'm done!
